# Generated by Django 5.2.4 on 2025-07-23 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_complete_alter_order_date_of_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='shop.order'),
        ),
    ]
